### ISSUE TITLE
Fails to install on Windows 10

### ISSUE THREAD

**Issue by abarto** [fisadev/simpyt#27]
The app fails silently on Windows 10. Double clicking on the .pyz file opens up a command prompt window without any messages and it closes after a few seconds.

If you try to run the launcher from the console you get the following message:
![VirtualBox_Windows 10_06_12_2023_10_56_18](https://github.com/fisadev/simpyt/assets/5585302/0e7205d8-761c-4dc4-97f6-d1b11b44fd59)

**Comment by fisadev** [comment]
Hi! Could you check what python version is C:\Users\vboxuser\AppData\Local\Programs\Python\Launcher\py.exe?

Also, does the virtual machine have access to the internet? And could it be that a firewall or antivirus is blocking the app from downloading dependencies?

**Comment by abarto** [comment]
It's a fresh Python 3.12.0 downloaded from the box itself. The system's pip (`python.exe -m pip`) can download dependencies without issues.

**Comment by abarto** [comment]
Same problem even with the firewall disabled.

**Comment by fisadev** [comment]
Ok. Could you try running the command that the pyz tried to run? Using the pip3.exe from its virtualenv in AppData, pointing to those requirements.

**Comment by abarto** [comment]
```
C:\Users\vboxuser\Downloads>C:\Users\vboxuser\AppData\Local\pyempaq\simpyt-20231206134729\project_venv\Scripts\pip3.exe install -r C:\Users\vboxuser\AppData\Local\pyempaq\simpyt-20231206134729\orig\requirements.txt
Ignoring python-rtmidi: markers 'platform_system == "Linux"' don't match your environment
Collecting flask==2.3.2 (from -r C:\Users\vboxuser\AppData\Local\pyempaq\simpyt-20231206134729\orig\requirements.txt (line 1))
  Using cached Flask-2.3.2-py3-none-any.whl (96 kB)
Collecting jinja2==3.1.2 (from -r C:\Users\vboxuser\AppData\Local\pyempaq\simpyt-20231206134729\orig\requirements.txt (line 2))
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting pyyaml==6.0 (from -r C:\Users\vboxuser\AppData\Local\pyempaq\simpyt-20231206134729\orig\requirements.txt (line 3))
  Using cached PyYAML-6.0.tar.gz (124 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      running egg_info
      writing lib\PyYAML.egg-info\PKG-INFO
      writing dependency_links to lib\PyYAML.egg-info\dependency_links.txt
      writing top-level names to lib\PyYAML.egg-info\top_level.txt
      Traceback (most recent call last):
        File "C:\Users\vboxuser\AppData\Local\pyempaq\simpyt-20231206134729\project_venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\vboxuser\AppData\Local\pyempaq\simpyt-20231206134729\project_venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\vboxuser\AppData\Local\pyempaq\simpyt-20231206134729\project_venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\vboxuser\AppData\Local\Temp\pip-build-env-96giu3xk\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\vboxuser\AppData\Local\Temp\pip-build-env-96giu3xk\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\vboxuser\AppData\Local\Temp\pip-build-env-96giu3xk\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 288, in <module>
        File "C:\Users\vboxuser\AppData\Local\Temp\pip-build-env-96giu3xk\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\vboxuser\AppData\Local\Temp\pip-build-env-96giu3xk\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\vboxuser\AppData\Local\Temp\pip-build-env-96giu3xk\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\vboxuser\AppData\Local\Temp\pip-build-env-96giu3xk\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\vboxuser\AppData\Local\Temp\pip-build-env-96giu3xk\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\vboxuser\AppData\Local\Temp\pip-build-env-96giu3xk\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\vboxuser\AppData\Local\Temp\pip-build-env-96giu3xk\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 321, in run
          self.find_sources()
        File "C:\Users\vboxuser\AppData\Local\Temp\pip-build-env-96giu3xk\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 329, in find_sources
          mm.run()
        File "C:\Users\vboxuser\AppData\Local\Temp\pip-build-env-96giu3xk\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 551, in run
          self.add_defaults()
        File "C:\Users\vboxuser\AppData\Local\Temp\pip-build-env-96giu3xk\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 589, in add_defaults
          sdist.add_defaults(self)
        File "C:\Users\vboxuser\AppData\Local\Temp\pip-build-env-96giu3xk\overlay\Lib\site-packages\setuptools\command\sdist.py", line 112, in add_defaults
          super().add_defaults()
        File "C:\Users\vboxuser\AppData\Local\Temp\pip-build-env-96giu3xk\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "C:\Users\vboxuser\AppData\Local\Temp\pip-build-env-96giu3xk\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<string>", line 204, in get_source_files
        File "C:\Users\vboxuser\AppData\Local\Temp\pip-build-env-96giu3xk\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: C:\Users\vboxuser\AppData\Local\pyempaq\simpyt-20231206134729\project_venv\Scripts\python.exe -m pip install --upgrade pip
```

**Comment by abarto** [comment]
Seems to be a `pyyaml` issue https://github.com/yaml/pyyaml/issues/601.

**Comment by fisadev** [comment]
Thanks for the info, yes, seems to be related to that. I'll try alternatives tonight, to see if I can solve it from Simpyt's side.

**Comment by fisadev** [comment]
Hi! I've been working on this, and sadly though there are ways of fixing it, python 3.12 brings a whole other set of problems with pygame, which simpyt internally uses for a few things. So I'll put a notice in the website that python 3.11 should be used instead, for now, until those issues have been solved. Sorry for the inconveniences!
